# Acordeón de pandas

 En esta nota verememos ejemplos de los comandos basicos de pandas utilizando una base de datos generica.

 El primer paso es importar la librería pandas como se muestra en la siguiente celda

In [87]:
import pandas as pd

## Leer un archivos .csv

Para extraer la información de un archivo .csv es necesario tener el archivo en la misma carpeta que esta nota, para el ejemplo de hoy usaremos el `archivo base_generica_pandas.csv`. Un archivo se lee utilizando el método `read_csv("nombre del archivo")` y guardarlo en una variable `df`

In [88]:
df = pd.read_csv("base_generica_pandas.csv")

Para explorar esta base podemos utilizar el método `head()` para mostrar las primeras 5 filas de la tabla, si quisieramos ver "n" filas podemos usar `head(n)`

In [89]:
df.head(67)

      col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
0   380.79    49  56.4     1    B    Sur  0.294     5   No   Alto
1   951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
2   734.67    49  57.2     2    C  Norte  0.697     5   Sí   Alto
3   602.67    21  63.9     0    A  Norte  0.384     3   Sí   Alto
4   164.46    47  37.4     7    D    Sur  0.737     3   Sí  Medio
..     ...   ...   ...   ...  ...    ...    ...   ...  ...    ...
62  830.45    40  35.8     7    D   Este  0.757     5   No   Alto
63  363.19    54  41.0     6    C  Norte  0.047     2   Sí   Alto
64  288.13    49  48.3     1    B  Oeste  0.269     2   No   Alto
65  547.27    50  23.8     0    C    Sur  0.022     3   Sí  Medio
66  149.51    18  29.9    10    D  Norte  0.498     3   Sí   Alto

[67 rows x 10 columns]

El metodo tail muestra los ultimos 5 elementos por default, pero es posible mostrar los ultimos n

In [90]:
df.tail(67)

      col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
33  949.40    18  33.3     5    A    Sur  0.165     2   No  Medio
34  965.98    44  63.0     8    C  Oeste  0.411     1   Sí   Bajo
35  810.31    30  64.4     4    A   Este  0.778     2   No   Bajo
36  311.57    58  56.3     0    C   Este  0.480     5   Sí  Medio
37  106.70    20  21.7     3    A  Norte  0.985     3   No   Bajo
..     ...   ...   ...   ...  ...    ...    ...   ...  ...    ...
95  498.86    43  47.7     8    B    Sur  0.459     2   Sí   Bajo
96  527.51    20  44.4     6    C   Este  0.842     2   Sí   Alto
97  433.27    36  30.6     3    D  Norte  0.769     3   Sí   Bajo
98   35.16    37  38.5     9    A  Norte  0.066     3   Sí   Bajo
99  116.81    49  56.3     4    B    Sur  0.046     5   Sí   Bajo

[67 rows x 10 columns]

El tamaño de la tabla se muestra con `.shape`. Donde el primer numero representa la cantidad de filas mientras la segunda cantidad representan la cantidad de columnas

In [91]:
df.shape

(100, 10)

El nombre de las columnas de un datagrame es accesible a través del atributo `columns`

In [92]:
df.columns

Index(['col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7', 'col8', 'col9',
       'col10'],
      dtype='object')

El método `.info()` muestra una tabla con la información de la tabla:
* Nombre de la columna
* Cantidad de nulos
* Tipos de datos
* Espacio en memoria (RAM)

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    100 non-null    float64
 1   col2    100 non-null    int64
 2   col3    100 non-null    float64
 3   col4    100 non-null    int64
 4   col5    100 non-null    object
 5   col6    100 non-null    object
 6   col7    100 non-null    float64
 7   col8    100 non-null    int64
 8   col9    100 non-null    object
 9   col10   100 non-null    object
dtypes: float64(3), int64(3), object(4)
memory usage: 7.9+ KB

# Manejo de columnas

Es posible seleccionar una o varias columnas:
* Una columna
* Dos columnas
* Una lista de columnas

La sintaxis general es `df[las columnas que quiero]`

### Ejemplo para una columna
Para seleccionar la columna `col5` usamos `df["col5"]`

In [94]:
df["col5"]

0     B
1     A
2     C
3     A
4     D
     ..
95    B
96    C
97    D
98    A
99    B
Name: col5, Length: 100, dtype: object

### Ejemplo para dos columnas

Para seleccionar dos columnas la sintaxis general es `df[["col8","col7"]]`, la diferencia con seleccionar una columna es que en esta ocasión hay doble corchete:

In [95]:
df[["col8","col7"]]

    col8   col7
0      5  0.294
1      2  0.996
2      5  0.697
3      3  0.384
4      3  0.737
..   ...    ...
95     2  0.459
96     2  0.842
97     3  0.769
98     3  0.066
99     5  0.046

[100 rows x 2 columns]

### Ejemplo para seleccioar varias columnas
En general para seleccionar varias columnas es necesario escribir la lista de las columnas y pasarla con corchetes al dataframe, por ejemplo, si queremos las columnas `col1`,`col10`,`col6` y `col8`, podemos utilizar la siguiente sintasis

In [96]:
columnas_seleccionadas = ["col1","col10","col6","col8"]
df[columnas_seleccionadas]

      col1  col10   col6  col8
0   380.79   Alto    Sur     5
1   951.21  Medio  Oeste     2
2   734.67   Alto  Norte     5
3   602.67   Alto  Norte     3
4   164.46  Medio    Sur     3
..     ...    ...    ...   ...
95  498.86   Bajo    Sur     2
96  527.51   Alto   Este     2
97  433.27   Bajo  Norte     3
98   35.16   Bajo  Norte     3
99  116.81   Bajo    Sur     5

[100 rows x 4 columns]

# Filtrar datos
Al crear una condición sobre una columna estamos creando una mascara logica (una columna True o False por cada fila que cumpla la condicion), por ejemplo `df["col6"] == "Sur"` crea una columna que será True en aquellas filas donde el valor sea "Sur" y False cuando no lo sea.

In [97]:
df["col6"] == "Sur"

0      True
1     False
2     False
3     False
4      True
      ...
95     True
96    False
97    False
98    False
99     True
Name: col6, Length: 100, dtype: bool

Para acceder a la tabla completa en la que se cumpla la condición `df["col6"] == "Sur"` sólo basta con agregarlo entre corcente en el dataframe: `df[df["col6"] == "Sur"]`. El resultado contiene las filas y columnas del dataframe en las cuales la columna `col6` tenga el valor "Sur"

In [98]:
df[df["col6"] == "Sur"]

      col1  col2  col3  col4 col5 col6   col7  col8 col9  col10
0   380.79    49  56.4     1    B  Sur  0.294     5   No   Alto
4   164.46    47  37.4     7    D  Sur  0.737     3   Sí  Medio
6    67.50    40  78.1     9    A  Sur  0.959     3   Sí   Bajo
9   710.99    32  42.2     4    A  Sur  0.107     4   Sí  Medio
11  970.21    46  55.7     4    B  Sur  0.170     1   No   Bajo
13  220.22    30  57.5     8    A  Sur  0.388     3   Sí   Bajo
14  190.01    49  47.8     4    D  Sur  0.229     3   No  Medio
18  437.63    19  51.6     0    C  Sur  0.453     2   No  Medio
24  461.51    61  22.3     0    D  Sur  0.133     4   Sí  Medio
33  949.40    18  33.3     5    A  Sur  0.165     2   No  Medio
39  445.75    23  52.2     9    A  Sur  0.750     2   Sí   Alto
42   44.04    26  49.8     6    D  Sur  0.569     3   No   Bajo
43  910.23    54  56.2     3    D  Sur  0.064     5   Sí  Medio
46  318.59    61  69.5     6    A  Sur  0.014     4   No   Alto
50  969.89    49  49.9     4    D  Sur  0.750     5   No   Bajo
52  940.10    58  72.2     1    A  Sur  0.585     2   Sí   Alto
53  895.88    29  56.0     3    A  Sur  0.726     4   No   Alto
65  547.27    50  23.8     0    C  Sur  0.022     3   Sí  Medio
73  817.31    49  43.3     2    C  Sur  0.792     2   Sí   Bajo
75  731.72    28  39.1     4    D  Sur  0.480     1   No   Bajo
76  773.56    34  23.0     2    A  Sur  0.421     1   Sí   Bajo
85  331.93    33  80.0     2    C  Sur  0.555     2   Sí  Medio
95  498.86    43  47.7     8    B  Sur  0.459     2   Sí   Bajo
99  116.81    49  56.3     4    B  Sur  0.046     5   Sí   Bajo

### Filtrar por más de una condición
Para filtrar por más de una condición basta con separar las condiciones por paréntesis y conectarlos con los operadores lógicos `&` (and), `|` (or), `~` (not), ejemplo:

*las filas cuya columna 6 sea "Sur" y col5 diferente de "B"
`(df["col6"]=="Sur") & (df["col5"]!="B")`

*Las filas cuya columna 5 sea "A" o columna 6 sea "Norte"
`(df["col5"]=="A") | (df["col6"] == "Norte")

In [99]:
df[(df["col6"]=="Sur") & (df["col5"]!="B")]

      col1  col2  col3  col4 col5 col6   col7  col8 col9  col10
4   164.46    47  37.4     7    D  Sur  0.737     3   Sí  Medio
6    67.50    40  78.1     9    A  Sur  0.959     3   Sí   Bajo
9   710.99    32  42.2     4    A  Sur  0.107     4   Sí  Medio
13  220.22    30  57.5     8    A  Sur  0.388     3   Sí   Bajo
14  190.01    49  47.8     4    D  Sur  0.229     3   No  Medio
18  437.63    19  51.6     0    C  Sur  0.453     2   No  Medio
24  461.51    61  22.3     0    D  Sur  0.133     4   Sí  Medio
33  949.40    18  33.3     5    A  Sur  0.165     2   No  Medio
39  445.75    23  52.2     9    A  Sur  0.750     2   Sí   Alto
42   44.04    26  49.8     6    D  Sur  0.569     3   No   Bajo
43  910.23    54  56.2     3    D  Sur  0.064     5   Sí  Medio
46  318.59    61  69.5     6    A  Sur  0.014     4   No   Alto
50  969.89    49  49.9     4    D  Sur  0.750     5   No   Bajo
52  940.10    58  72.2     1    A  Sur  0.585     2   Sí   Alto
53  895.88    29  56.0     3    A  Sur  0.726     4   No   Alto
65  547.27    50  23.8     0    C  Sur  0.022     3   Sí  Medio
73  817.31    49  43.3     2    C  Sur  0.792     2   Sí   Bajo
75  731.72    28  39.1     4    D  Sur  0.480     1   No   Bajo
76  773.56    34  23.0     2    A  Sur  0.421     1   Sí   Bajo
85  331.93    33  80.0     2    C  Sur  0.555     2   Sí  Medio

# Ordenar Datos
Ordenaremos el DataFrame utilizando una o varias columnas. Ya sea de menor a mayor o de mayor a menor

In [100]:
df.sort_values("col1") #Menor a mayor (esto ya es por defecto)

      col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
72   15.47    23  63.2     0    D  Norte  0.088     1   No   Alto
10   30.38    60  50.2     9    D  Norte  0.336     4   No  Medio
98   35.16    37  38.5     9    A  Norte  0.066     3   Sí   Bajo
42   44.04    26  49.8     6    D    Sur  0.569     3   No   Bajo
58   54.78    34  48.1     0    D   Este  0.251     3   No   Alto
..     ...   ...   ...   ...  ...    ...    ...   ...  ...    ...
1   951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
34  965.98    44  63.0     8    C  Oeste  0.411     1   Sí   Bajo
50  969.89    49  49.9     4    D    Sur  0.750     5   No   Bajo
11  970.21    46  55.7     4    B    Sur  0.170     1   No   Bajo
69  987.02    61  70.8     1    C  Norte  0.308     4   No   Bajo

[100 rows x 10 columns]

In [101]:
df.sort_values("col1", ascending = False) #De mayor a menor

      col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
69  987.02    61  70.8     1    C  Norte  0.308     4   No   Bajo
11  970.21    46  55.7     4    B    Sur  0.170     1   No   Bajo
50  969.89    49  49.9     4    D    Sur  0.750     5   No   Bajo
34  965.98    44  63.0     8    C  Oeste  0.411     1   Sí   Bajo
1   951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
..     ...   ...   ...   ...  ...    ...    ...   ...  ...    ...
58   54.78    34  48.1     0    D   Este  0.251     3   No   Alto
42   44.04    26  49.8     6    D    Sur  0.569     3   No   Bajo
98   35.16    37  38.5     9    A  Norte  0.066     3   Sí   Bajo
10   30.38    60  50.2     9    D  Norte  0.336     4   No  Medio
72   15.47    23  63.2     0    D  Norte  0.088     1   No   Alto

[100 rows x 10 columns]

# Estadisticas descriptivas

Para obtener la estadistica de una columna basta con seleccionar la columna y aplicar el metodo, por ejemplo la media es `.mean()`, el maximo `.max()`, la mediana `.median()`, por ejemplo 

* `df["col1"].mean()` Calcula la media

In [102]:
df["col1"].mean()

np.float64(475.4793000000001)

# Trabajar con variables categoricas
Para analizar variables de texto o categorías, utilizamos `value_counts()` para contar cuántas veces aparece cada valor, `unique()` para obtener una lista de los valores distintos (osea que variables hay), o `nunique()` para saber la cantidad exacta de valores diferentes (cuantas variables hay).

In [103]:
conteo_categorías = df["col10"].value_counts()
display(conteo_categorías)

col10
Bajo     36
Alto     34
Medio    30
Name: count, dtype: int64

In [104]:
valores_unicos = df["col9"].unique()
valores_unicos

array(['No', 'Sí'], dtype=object)

In [105]:
valores_no_unicos = df["col9"].nunique()
valores_no_unicos

2

# .groupby

In [106]:
df.groupby("col10")[["col1","col3"]].mean()

             col1       col3
col10
Alto   480.194412  51.141176
Bajo   473.109722  46.633333
Medio  472.979000  47.156667

In [107]:
df.groupby(["col10","col5","col9"])[["col1","col3"]].mean()

                       col1       col3
col10 col5 col9
Alto  A    No    713.192500  50.525000
           Sí    395.991667  50.533333
      B    No    389.716667  44.066667
           Sí    498.990000  59.100000
      C    No    505.217500  57.275000
           Sí    581.526667  47.150000
      D    No    379.355714  53.914286
           Sí    382.620000  46.850000
Bajo  A    No    423.932222  50.100000
           Sí    343.237143  49.000000
      B    No    740.536667  40.433333
           Sí    254.590000  50.200000
      C    No    987.020000  70.800000
           Sí    525.102000  52.260000
      D    No    585.535000  36.400000
           Sí    468.462500  33.825000
Medio A    No    440.346000  43.600000
           Sí    790.663333  37.166667
      B    No    549.550000  61.466667
           Sí    317.870000  26.600000
      C    No    350.266000  50.720000
           Sí    433.078000  49.980000
      D    No    479.392500  45.400000
           Sí    453.710000  47.275000

# Crear y modificar columnas
Para hacer una columna nueva, solo pones el nombre que quieras entre corchetes y le dices a qué va a ser igual. Puede ser una operación con otras columnas (como sumarlas, que es lo que hacemos en el ejemplo) o meterle un valor fijo a todas las filas.

In [108]:
df["suma_col1_col3"] = df["col1"] + df["col3"]
df[["col1", "col3", "suma_col1_col3"]].head()

     col1  col3  suma_col1_col3
0  380.79  56.4          437.19
1  951.21  13.0          964.21
2  734.67  57.2          791.87
3  602.67  63.9          666.57
4  164.46  37.4          201.86

# Combinar operaciones
Por ejemplo aqui separamos solo las filas que digan `"sur"`, de ahí obtenemos el promedio de la `"col1"` por cada categoria de la `"col10"` y la ordenamos de mayor a menor

In [109]:
resultado_final = df[df["col6"] == "Sur"].groupby("col10")[["col1"]].mean().sort_values("col1",ascending=False)
resultado_final

             col1
col10
Alto   596.222000
Medio  522.603333
Bajo   521.012000