In [10]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv("cartera_seguros_riesgos.csv")

In [12]:
display(df)

,Edad,Sexo,Fumador,Region,Horas_Ejercicio,IMC,Presion_Arterial,Distancia_Hospital_km,Sueldo_Mensual,Suma_Vida_MXN,Costo_Siniestros_MXN
0,35,F,No,Bajio,6.7,24.84,114,19.5,35620.48,856277.15,21779.27
1,35,M,No,Sur,8.0,22.13,116,20.2,27934.40,646956.28,14885.19
2,61,F,No,Sur,2.5,25.66,131,13.0,44434.12,1068570.34,27422.74
3,35,F,No,Bajio,6.2,23.29,119,2.3,20399.25,502654.85,23603.50
4,36,F,No,Norte,5.7,21.81,114,23.7,36439.94,855790.66,23221.75
...,...,...,...,...,...,...,...,...,...,...,...
995,60,F,No,Bajio,4.4,24.26,127,3.9,34956.54,848863.95,29949.56
996,31,F,No,Bajio,3.3,25.44,112,24.3,42054.92,1003535.68,17497.88
997,37,M,No,Sur,3.9,23.33,117,27.5,41066.19,954517.82,17977.72
998,37,M,No,Sur,5.3,24.06,118,22.9,36052.06,882765.63,21562.46
999,60,F,No,Sur,1.6,26.22,145,24.9,34627.16,819426.16,30828.55

In [13]:
display(df.head())

,Edad,Sexo,Fumador,Region,Horas_Ejercicio,IMC,Presion_Arterial,Distancia_Hospital_km,Sueldo_Mensual,Suma_Vida_MXN,Costo_Siniestros_MXN
0,35,F,No,Bajio,6.7,24.84,114,19.5,35620.48,856277.15,21779.27
1,35,M,No,Sur,8.0,22.13,116,20.2,27934.40,646956.28,14885.19
2,61,F,No,Sur,2.5,25.66,131,13.0,44434.12,1068570.34,27422.74
3,35,F,No,Bajio,6.2,23.29,119,2.3,20399.25,502654.85,23603.50
4,36,F,No,Norte,5.7,21.81,114,23.7,36439.94,855790.66,23221.75

In [14]:
display(df.tail())

,Edad,Sexo,Fumador,Region,Horas_Ejercicio,IMC,Presion_Arterial,Distancia_Hospital_km,Sueldo_Mensual,Suma_Vida_MXN,Costo_Siniestros_MXN
995,60,F,No,Bajio,4.4,24.26,127,3.9,34956.54,848863.95,29949.56
996,31,F,No,Bajio,3.3,25.44,112,24.3,42054.92,1003535.68,17497.88
997,37,M,No,Sur,3.9,23.33,117,27.5,41066.19,954517.82,17977.72
998,37,M,No,Sur,5.3,24.06,118,22.9,36052.06,882765.63,21562.46
999,60,F,No,Sur,1.6,26.22,145,24.9,34627.16,819426.16,30828.55

In [15]:
df_no_fumadores = df[df["Fumador"] == "No"]

In [16]:
display(df_no_fumadores.head())

,Edad,Sexo,Fumador,Region,Horas_Ejercicio,IMC,Presion_Arterial,Distancia_Hospital_km,Sueldo_Mensual,Suma_Vida_MXN,Costo_Siniestros_MXN
0,35,F,No,Bajio,6.7,24.84,114,19.5,35620.48,856277.15,21779.27
1,35,M,No,Sur,8.0,22.13,116,20.2,27934.40,646956.28,14885.19
2,61,F,No,Sur,2.5,25.66,131,13.0,44434.12,1068570.34,27422.74
3,35,F,No,Bajio,6.2,23.29,119,2.3,20399.25,502654.85,23603.50
4,36,F,No,Norte,5.7,21.81,114,23.7,36439.94,855790.66,23221.75

In [17]:
df_no_fumadores["Costo_Siniestros_MXN"].mean()

np.float64(22711.682065663474)

In [18]:
df[df["Fumador"]!= "No"]["Costo_Siniestros_MXN"].mean()

np.float64(55980.09204460967)

In [19]:
df_no_fumadores["Presion_Arterial"].max()

np.int64(145)

In [20]:
df_fumadores["Presion_Arterial"].max()

NameError: name 'df_fumadores' is not defined

In [ ]:
df.head()

,Edad,Sexo,Fumador,Region,Horas_Ejercicio,IMC,Presion_Arterial,Distancia_Hospital_km,Sueldo_Mensual,Suma_Vida_MXN,Costo_Siniestros_MXN
0,35,F,No,Bajio,6.7,24.84,114,19.5,35620.48,856277.15,21779.27
1,35,M,No,Sur,8.0,22.13,116,20.2,27934.40,646956.28,14885.19
2,61,F,No,Sur,2.5,25.66,131,13.0,44434.12,1068570.34,27422.74
3,35,F,No,Bajio,6.2,23.29,119,2.3,20399.25,502654.85,23603.50
4,36,F,No,Norte,5.7,21.81,114,23.7,36439.94,855790.66,23221.75

In [ ]:
df["Porcentaje_sueldo_siniestro"] = df["Costo_Siniestros_MXN"]/ df["Sueldo_Mensual"]
display(df.head())

,Edad,Sexo,Fumador,Region,Horas_Ejercicio,IMC,Presion_Arterial,Distancia_Hospital_km,Sueldo_Mensual,Suma_Vida_MXN,Costo_Siniestros_MXN,Porcentaje_sueldo_siniestro
0,35,F,No,Bajio,6.7,24.84,114,19.5,35620.48,856277.15,21779.27,0.611426
1,35,M,No,Sur,8.0,22.13,116,20.2,27934.40,646956.28,14885.19,0.532862
2,61,F,No,Sur,2.5,25.66,131,13.0,44434.12,1068570.34,27422.74,0.617155
3,35,F,No,Bajio,6.2,23.29,119,2.3,20399.25,502654.85,23603.50,1.157077
4,36,F,No,Norte,5.7,21.81,114,23.7,36439.94,855790.66,23221.75,0.637261

In [ ]:
df[df["Porcentaje_sueldo_siniestro"] >= 1].count()

Edad                           274
Sexo                           274
Fumador                        274
Region                         274
Horas_Ejercicio                274
IMC                            274
Presion_Arterial               274
Distancia_Hospital_km          274
Sueldo_Mensual                 274
Suma_Vida_MXN                  274
Costo_Siniestros_MXN           274
Porcentaje_sueldo_siniestro    274
dtype: int64

In [ ]:
df[(df["Edad"]>27) & (df["Fumador"]=="Si")]

,Edad,Sexo,Fumador,Region,Horas_Ejercicio,IMC,Presion_Arterial,Distancia_Hospital_km,Sueldo_Mensual,Suma_Vida_MXN,Costo_Siniestros_MXN
5,55,M,Si,Norte,8.3,21.98,116,20.7,41203.39,965893.55,48506.06
14,46,M,Si,Bajio,6.2,20.89,117,7.2,35942.35,856894.06,53653.05
15,41,F,Si,Bajio,3.3,26.03,117,20.0,30327.37,708049.55,61379.73
19,52,F,Si,Centro,7.8,22.23,125,24.4,25486.17,593515.66,49693.47
28,35,M,Si,Centro,6.7,19.78,125,7.0,34100.72,824669.42,25662.40
...,...,...,...,...,...,...,...,...,...,...,...
981,34,M,Si,Norte,8.1,21.42,111,23.6,44526.21,1088925.06,49451.20
983,58,F,Si,Sur,2.3,29.91,135,2.7,41169.59,994004.25,62531.85
990,32,M,Si,Bajio,0.8,23.77,119,18.2,24613.15,611211.34,50836.92
992,47,M,Si,Bajio,7.5,22.83,133,2.0,54559.19,1319719.09,61095.82
993,41,M,Si,Norte,0.5,28.09,119,16.7,31102.68,757580.34,51553.95

In [25]:
df.groupby("df_no_fumadores")

KeyError: 'df_no_fumadores'