In [1]:
import pandas as pd
pd.read_csv("dataset_boletaje_ecommerce.csv")

,ID_Transaccion,Edad_Usuario,Meses_Antiguedad,Ingreso_Mensual_Estimado,Score_Riesgo_Fraude,Tiempo_Plataforma_Min,Ticket_Promedio_MXN,Boletos_Comprados_Anual,Monto_Reembolso_Historico,Metodo_Pago,Origen_Trafico
0,10001,27,7,22451.13,54.4,29.9,1293.02,10,2519.27,Tarjeta_Debito,Orgánico
1,10002,45,14,46364.60,61.8,16.0,750.23,6,124.50,Tarjeta_Credito,Campaña_Ads
2,10003,42,1,42425.36,66.3,10.5,442.53,1,551.21,Cartera_Digital,Referido
3,10004,32,29,34737.96,66.2,21.6,1044.77,2,172.74,Tarjeta_Credito,Orgánico
4,10005,28,1,29476.35,78.1,39.3,1010.80,5,137.91,Tarjeta_Debito,Campaña_Ads
...,...,...,...,...,...,...,...,...,...,...,...
1495,11496,18,8,25961.25,75.8,44.7,1060.77,5,623.19,Cartera_Digital,Orgánico
1496,11497,40,19,48427.29,50.8,26.1,1002.97,3,1478.15,Tarjeta_Debito,Campaña_Ads
1497,11498,29,9,34105.82,53.1,18.7,710.41,4,2980.95,Tarjeta_Credito,Campaña_Ads
1498,11499,33,16,41652.80,61.9,14.7,582.97,1,684.01,Tarjeta_Debito,Orgánico
1499,11500,25,1,29401.90,63.0,10.7,482.41,4,462.96,Tarjeta_Debito,Campaña_Ads

In [2]:
df = pd.read_csv("dataset_boletaje_ecommerce.csv")

In [3]:
#Tomar el df con columnas (Edad y Score Riesgo)


df[["Edad_Usuario","Score_Riesgo_Fraude"]]

      Edad_Usuario  Score_Riesgo_Fraude
0               27                 54.4
1               45                 61.8
2               42                 66.3
3               32                 66.2
4               28                 78.1
...            ...                  ...
1495            18                 75.8
1496            40                 50.8
1497            29                 53.1
1498            33                 61.9
1499            25                 63.0

[1500 rows x 2 columns]

In [4]:
#Filtrar por usuarios nuevos (meses menor a 2)
Usuarios_Nuevos = df[df["Meses_Antiguedad"]<2]
Usuarios_Nuevos

,ID_Transaccion,Edad_Usuario,Meses_Antiguedad,Ingreso_Mensual_Estimado,Score_Riesgo_Fraude,Tiempo_Plataforma_Min,Ticket_Promedio_MXN,Boletos_Comprados_Anual,Monto_Reembolso_Historico,Metodo_Pago,Origen_Trafico
2,10003,42,1,42425.36,66.3,10.5,442.53,1,551.21,Cartera_Digital,Referido
4,10005,28,1,29476.35,78.1,39.3,1010.80,5,137.91,Tarjeta_Debito,Campaña_Ads
5,10006,28,1,43889.50,72.3,2.7,263.73,2,608.53,Cartera_Digital,Referido
7,10008,26,1,35660.15,59.6,31.7,1033.25,0,341.32,Tarjeta_Credito,Referido
12,10013,37,1,40110.64,55.3,29.1,1375.65,6,333.03,Tarjeta_Credito,Orgánico
...,...,...,...,...,...,...,...,...,...,...,...
1481,11482,33,1,44122.57,59.3,12.5,466.32,4,458.52,Cartera_Digital,Referido
1484,11485,22,1,23599.42,83.8,20.1,667.14,4,606.33,Tarjeta_Credito,Referido
1492,11493,24,1,29397.69,54.2,21.1,733.66,0,1005.67,Tarjeta_Debito,Orgánico
1494,11495,35,1,36361.94,45.0,11.2,363.65,3,340.94,Tarjeta_Credito,Campaña_Ads
1499,11500,25,1,29401.90,63.0,10.7,482.41,4,462.96,Tarjeta_Debito,Campaña_Ads

In [5]:
#Filtar por usuarios antiguos (Meses mayores a 12)
Usuarios_Viejos = df[df["Meses_Antiguedad"]>12]
Usuarios_Viejos

,ID_Transaccion,Edad_Usuario,Meses_Antiguedad,Ingreso_Mensual_Estimado,Score_Riesgo_Fraude,Tiempo_Plataforma_Min,Ticket_Promedio_MXN,Boletos_Comprados_Anual,Monto_Reembolso_Historico,Metodo_Pago,Origen_Trafico
1,10002,45,14,46364.60,61.8,16.0,750.23,6,124.50,Tarjeta_Credito,Campaña_Ads
3,10004,32,29,34737.96,66.2,21.6,1044.77,2,172.74,Tarjeta_Credito,Orgánico
9,10010,42,37,55459.68,56.5,6.2,433.58,3,901.81,Tarjeta_Credito,Campaña_Ads
11,10012,32,13,28540.98,65.0,25.7,417.38,1,2570.85,Tarjeta_Debito,Orgánico
13,10014,26,13,28797.85,50.8,41.1,1151.17,7,1990.20,Tarjeta_Debito,Campaña_Ads
...,...,...,...,...,...,...,...,...,...,...,...
1490,11491,30,24,44508.70,50.0,22.6,517.30,10,113.45,Tarjeta_Credito,Campaña_Ads
1491,11492,34,14,33093.59,63.3,5.8,3389.82,0,507.68,Tarjeta_Debito,Orgánico
1493,11494,26,14,24979.26,47.0,16.7,446.53,1,81.81,Tarjeta_Credito,Campaña_Ads
1496,11497,40,19,48427.29,50.8,26.1,1002.97,3,1478.15,Tarjeta_Debito,Campaña_Ads
1498,11499,33,16,41652.80,61.9,14.7,582.97,1,684.01,Tarjeta_Debito,Orgánico

In [6]:
#Hay mas antiguos o nuevos?
(Usuarios_Nuevos.count())-(Usuarios_Viejos.count())
#Hay mas viejos por la diferencia que generan los viejos al restarselo a los nuevos

ID_Transaccion              -297
Edad_Usuario                -297
Meses_Antiguedad            -297
Ingreso_Mensual_Estimado    -297
Score_Riesgo_Fraude         -297
Tiempo_Plataforma_Min       -297
Ticket_Promedio_MXN         -297
Boletos_Comprados_Anual     -297
Monto_Reembolso_Historico   -297
Metodo_Pago                 -297
Origen_Trafico              -297
dtype: int64

In [7]:
df[["Edad_Usuario","Score_Riesgo_Fraude"]]

      Edad_Usuario  Score_Riesgo_Fraude
0               27                 54.4
1               45                 61.8
2               42                 66.3
3               32                 66.2
4               28                 78.1
...            ...                  ...
1495            18                 75.8
1496            40                 50.8
1497            29                 53.1
1498            33                 61.9
1499            25                 63.0

[1500 rows x 2 columns]

In [8]:
#Muestra el maximo de ticket promedio por método de pago

df["Ticket_Promedio_MXN"].describe()
df["Metodo_Pago"].max

<bound method Series.max of 0        Tarjeta_Debito
1       Tarjeta_Credito
2       Cartera_Digital
3       Tarjeta_Credito
4        Tarjeta_Debito
             ...
1495    Cartera_Digital
1496     Tarjeta_Debito
1497    Tarjeta_Credito
1498     Tarjeta_Debito
1499     Tarjeta_Debito
Name: Metodo_Pago, Length: 1500, dtype: object>

In [9]:
df.groupby("Origen_Trafico")["Ticket_Promedio_MXN"].sum()

Origen_Trafico
Campaña_Ads    655094.09
Orgánico       463046.03
Referido       126725.89
Name: Ticket_Promedio_MXN, dtype: float64

In [10]:
df.groupby(["Origen_Trafico","Metodo_Pago"])[["ID_Transaccion"]].count()

                                ID_Transaccion
Origen_Trafico Metodo_Pago
Campaña_Ads    Cartera_Digital             118
               Tarjeta_Credito             339
               Tarjeta_Debito              281
               Transferencia                40
Orgánico       Cartera_Digital              74
               Tarjeta_Credito             259
               Tarjeta_Debito              196
               Transferencia                29
Referido       Cartera_Digital              30
               Tarjeta_Credito              71
               Tarjeta_Debito               58
               Transferencia                 5