In [71]:
import pandas as pd 
pd.read_csv("https://raw.githubusercontent.com/vida092/diplomado_big_data/refs/heads/main/peliculas.csv")

,id,titulo,fecha_estreno,genero,duracion_min,presupuesto_musd,taquilla_musd,popularidad,rating,votos,idioma_original,adulto
0,1711051,100 Years,2099-12-31,Sin género,0,0.0,0.0,0.26,0.0,0,en,False
1,1742644,American Static,2047-05-11,Ciencia ficción,186,0.0,0.0,0.24,0.0,0,en,False
2,1742657,September,2045-07-08,Terror,140,0.0,0.0,0.25,0.0,0,en,False
3,1370697,Light Years,2044-10-01,Sin género,7,0.0,0.0,0.69,0.0,0,en,False
4,1742658,Harvest,2043-10-03,Terror,184,0.0,0.0,0.21,0.0,0,en,False
...,...,...,...,...,...,...,...,...,...,...,...,...
95,806704,Batman: Parte 2,2028-02-17,Misterio,0,0.0,0.0,5.52,0.0,0,en,False
96,1662286,Золушка,2028-02-10,Sin género,0,0.0,0.0,0.94,0.0,0,ru,False
97,1625381,Heart Eyes 2,2028-02-10,Terror,0,0.0,0.0,0.51,0.0,0,en,False
98,1188748,"Murder, She Wrote",2028-02-03,Misterio,0,0.0,0.0,0.63,0.0,0,en,False
99,1634592,Endless Summer,2028-01-28,Drama,130,0.0,0.0,1.61,0.0,0,en,False

In [72]:
df = pd.read_csv("https://raw.githubusercontent.com/vida092/diplomado_big_data/refs/heads/main/peliculas.csv")

# 1.- ¿Cuántas películas hay en el dataset?
# 2.- ¿Cuántas variables o columnas contiene el dataset?

In [73]:
df.shape 
#1.-Hay entonces, 100 peliculas en la lista jeje 
#2.- y un total de 12 columnas

(100, 12)

# 3.- ¿Cuáles son las columnas que contiene el DataFrame? 
# 4.- ¿Qué tipo de dato tiene cada columna?

In [74]:
df.dtypes 
#3.- y 4.- Las que aparecen aqui abajo

id                    int64
titulo               object
fecha_estreno        object
genero               object
duracion_min          int64
presupuesto_musd    float64
taquilla_musd       float64
popularidad         float64
rating              float64
votos                 int64
idioma_original      object
adulto                 bool
dtype: object

# 5.- ¿Existen valores faltantes en el dataset?
# 6.- ¿Cuánta información contiene cada columna?

In [75]:
df.count()
# Como cada columna tiene 100 datos cada una, entonces no hay ningun valor faltante

id                  100
titulo              100
fecha_estreno       100
genero              100
duracion_min        100
presupuesto_musd    100
taquilla_musd       100
popularidad         100
rating              100
votos               100
idioma_original     100
adulto              100
dtype: int64

# 7.-¿Qué columnas contienen información numérica?
# 8.- ¿Qué columnas contienen información categórica o textual?

In [76]:
df.dtypes
#Las columnas que tienen información numérica son las que tienen "int64" y "float64", debido a que representan a los numeros enteros y Reales respectivamentes
#De igual forma, como ya dijimos cuales son las columnas que tienen datos numericos, entonces, las restantes serían las que contienen información textual o categorica

id                    int64
titulo               object
fecha_estreno        object
genero               object
duracion_min          int64
presupuesto_musd    float64
taquilla_musd       float64
popularidad         float64
rating              float64
votos                 int64
idioma_original      object
adulto                 bool
dtype: object

# 9.- Obtén únicamente la columna que contiene el título de las películas.

In [77]:
df[["titulo"]]

               titulo
0           100 Years
1     American Static
2           September
3         Light Years
4             Harvest
..                ...
95    Batman: Parte 2
96            Золушка
97       Heart Eyes 2
98  Murder, She Wrote
99     Endless Summer

[100 rows x 1 columns]

# 10.- Obtén únicamente la columna que contiene el rating de las películas.

In [78]:
df[["rating"]]

    rating
0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
..     ...
95     0.0
96     0.0
97     0.0
98     0.0
99     0.0

[100 rows x 1 columns]

# 11.- Obtén únicamente las columnas correspondientes al título, género y rating.

In [79]:
df[["titulo","genero","rating"]]

               titulo           genero  rating
0           100 Years       Sin género     0.0
1     American Static  Ciencia ficción     0.0
2           September           Terror     0.0
3         Light Years       Sin género     0.0
4             Harvest           Terror     0.0
..                ...              ...     ...
95    Batman: Parte 2         Misterio     0.0
96            Золушка       Sin género     0.0
97       Heart Eyes 2           Terror     0.0
98  Murder, She Wrote         Misterio     0.0
99     Endless Summer            Drama     0.0

[100 rows x 3 columns]

# 12.- Obtén las estadísticas descriptivas de las variables numéricas.
# 13.- ¿Cuál es el rating promedio de las películas?
# 14.- ¿Cuál es la duración promedio de las películas?

In [80]:
df.describe()
#Se responden todas las preguntas de la 12 a la 14, se muestran las estadisticas descriptivas, el rating promedio y la duración promedio, estas dos ultimos apareciendo en la segunda fila (mean)

,id,duracion_min,presupuesto_musd,taquilla_musd,popularidad,rating,votos
count,1.000000e+02,100.000000,100.0000,100.0,100.000000,100.0,100.0
mean,1.479390e+06,21.730000,8.1805,0.0,1.385000,0.0,0.0
std,3.080932e+05,50.850316,29.3839,0.0,2.069646,0.0,0.0
min,2.165270e+05,0.000000,0.0000,0.0,0.010000,0.0,0.0
25%,1.363082e+06,0.000000,0.0000,0.0,0.320000,0.0,0.0
50%,1.582366e+06,0.000000,0.0000,0.0,0.640000,0.0,0.0
75%,1.712100e+06,0.000000,0.0000,0.0,1.645000,0.0,0.0
max,1.752779e+06,186.000000,190.0000,0.0,14.950000,0.0,0.0

# 15.- ¿Cuál es la película con mayor duración?

In [81]:
df.groupby("duracion_min").max()[["titulo"]]
#La pelicula con más duración es la ultima de la lista en este caso

                               titulo
duracion_min
0                              나의 대통령
6               The Creation of Blobs
7                         Light Years
25                             Trójka
65                   Cannibal Kitchen
99                      Narco Shark 3
104                         Mr. Smith
109                   Act of Violence
111                           Headout
113           Captain Zero: The Movie
115               Detective Pikachu 2
130                    Endless Summer
138                        The Vaster
140                         September
144                           Vestige
152                         Mudflower
165                            Lament
180                  Lesai: The Movie
184                           Harvest
186                   American Static

# 16.- ¿Cuál es la película con mayor rating?

In [82]:
df[["titulo","rating"]].sort_values("rating", ascending = False)
#Esta es otra forma de resolver la anterior pero ahora con la columna "rating", pero como todas tiene 0 de rating pues no se ve

               titulo  rating
0           100 Years     0.0
1     American Static     0.0
2           September     0.0
3         Light Years     0.0
4             Harvest     0.0
..                ...     ...
95    Batman: Parte 2     0.0
96            Золушка     0.0
97       Heart Eyes 2     0.0
98  Murder, She Wrote     0.0
99     Endless Summer     0.0

[100 rows x 2 columns]

# 17.- ¿Cuál es la película que recibió más votos?

In [83]:
df[["titulo","votos"]].sort_values("votos", ascending = True)
#de igual forma, todos tienen 0 votos, entonces ninguna tiene mas votos

               titulo  votos
0           100 Years      0
1     American Static      0
2           September      0
3         Light Years      0
4             Harvest      0
..                ...    ...
95    Batman: Parte 2      0
96            Золушка      0
97       Heart Eyes 2      0
98  Murder, She Wrote      0
99     Endless Summer      0

[100 rows x 2 columns]

# 18.- ¿Qué géneros aparecen en el dataset y cuántas películas hay de cada género?

In [84]:
df.groupby("genero")[["titulo"]].count()

                 titulo
genero
Acción                9
Animación            14
Aventura              4
Bélica                1
Ciencia ficción       6
Comedia               2
Crimen                6
Documental            2
Drama                16
Familia               2
Fantasía              5
Historia              1
Misterio              2
Romance               1
Sin género           12
Suspense              2
Terror               15

# 19.- ¿Qué país aparece con mayor frecuencia?

In [85]:
df.groupby("idioma_original")["titulo"].count()
#quiero creer que se refería al idioma, si es así, el inglés es el que aparece con mayor frecuencia

idioma_original
cs     1
en    78
es     1
fr     3
hi     2
it     1
kn     1
ko     1
nl     1
pl     1
pt     2
ru     7
tr     1
Name: titulo, dtype: int64

# 20.- ¿Qué plataforma tiene más películas?

In [ ]:
#No aparece en la base de datos la plataforma, entonces no se puede responder jeje

# Reflexión

¿Qué método de Pandas te resultó más útil?

`.sortvalues` y el `.groupby`


¿Qué operación te costó más trabajo?

el `.sortvalues.`


¿Qué información sobre el dataset descubriste que no esperabas?

Que puedo ordenas de mayor a menor con el `.sortvalues("columna", ascending = False)`